#course-edge-service Dockerfile
FROM openjdk:8-jre
MAINTAINER mayanghua "yh_ma@qq.com"

COPY target/course-edge-service-1.0-SNAPSHOT.jar /course-edge-service.jar

ENTRYPOINT ["java","-jar","/course-edge-service.jar"]
