#user-edge-service Dockerfile
FROM openjdk:8-jre
MAINTAINER mayanghua "yh_ma@qq.com"

COPY target/user-edge-service-1.0-SNAPSHOT.jar /user-edge-service.jar

ENTRYPOINT ["java","-jar","/user-edge-service.jar"]
